# Generated by Django 4.1.4 on 2023-01-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course_app', '0016_alter_checkout_price'),
        ('Acount_app', '0021_teacher_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_income', to='Course_app.courses')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_income', to='Acount_app.teacher')),
            ],
        ),
    ]
