# Generated by Django 4.1.4 on 2022-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsmodel',
            name='resume',
            field=models.FileField(default=1, upload_to='media/request'),
            preserve_default=False,
        ),
    ]
