# Generated by Django 4.1.4 on 2022-12-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0002_requestsmodel_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsmodel',
            name='is_blogger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestsmodel',
            name='is_technical_team',
            field=models.BooleanField(default=False),
        ),
    ]
