# Generated by Django 4.1.4 on 2022-12-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0003_requestsmodel_is_blogger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsmodel',
            name='introduction',
            field=models.CharField(max_length=500),
        ),
    ]
