# Generated by Django 4.1.4 on 2022-12-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0004_alter_requestsmodel_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsmodel',
            name='introduction',
            field=models.TextField(),
        ),
    ]
