# Generated by Django 4.1.4 on 2023-01-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0005_alter_requestsmodel_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsmodel',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestsmodel',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
