# Generated by Django 4.1.4 on 2023-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0006_requestsmodel_is_employee_requestsmodel_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsmodel',
            name='position',
            field=models.CharField(choices=[('عضویت در کادر فنی', 'عضویت در کادر فنی'), ('وبلاگ نویس', 'وبلاگ نویس'), ('مدرس', 'مدرس'), ('کارمند', 'کارمند')], max_length=100),
        ),
    ]
