# Generated by Django 4.1.4 on 2023-01-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel_App', '0007_alter_requestsmodel_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsmodel',
            name='is_technical_team',
        ),
        migrations.AlterField(
            model_name='requestsmodel',
            name='position',
            field=models.CharField(choices=[('وبلاگ نویس', 'وبلاگ نویس'), ('مدرس', 'مدرس'), ('کارمند', 'کارمند')], max_length=100),
        ),
    ]
