# Generated by Django 4.1.4 on 2022-12-13 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acount_app', '0004_alter_user_image_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='media/video_cover')),
                ('titel', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('مقدماتی', 'مقدماتی'), ('مقدماتی تا پیشرفته', 'مقدماتی تا پیشرفته'), ('پیشرفته', 'پیشرفته'), ('پروژه محور و مقدماتی', 'پروژه محور و مقدماتی'), ('پیشرفته و پروژه محور', 'پیشرفته و پروژه محور')], default='مقدماتی', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('specifications', models.TextField()),
                ('Introduction_of_the_valley', models.TextField()),
                ('project_count', models.CharField(default='0', max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ManyToManyField(related_name='Corses', to='Course_app.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corses', to='Acount_app.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/video')),
                ('video_cover', models.ImageField(upload_to='media/video_cover')),
                ('time', models.CharField(default='00:00', max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corses_child', to='Course_app.courses')),
                ('topic_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_app_CoursesChild_topic_parent', to='Course_app.courseschild')),
            ],
        ),
    ]
