# Generated by Django 4.1.4 on 2022-12-13 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='Corses', to=settings.AUTH_USER_MODEL),
        ),
    ]
