# Generated by Django 4.1.4 on 2022-12-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0002_remove_courses_user_courses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschild',
            name='link_video',
            field=models.CharField(blank=True, default='aparat.com', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courseschild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corses_child', to='Course_app.courses'),
        ),
        migrations.AlterField(
            model_name='courseschild',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='courseschild',
            name='video_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/video_cover'),
        ),
    ]
