# Generated by Django 4.1.4 on 2022-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='crested',
            new_name='created',
        ),
    ]
