# Generated by Django 4.1.4 on 2022-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0005_rename_crested_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='introduction_video',
            field=models.FileField(default=1, upload_to='media/Video'),
            preserve_default=False,
        ),
    ]
