# Generated by Django 4.1.4 on 2022-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0006_courses_introduction_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschild',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
