# Generated by Django 4.1.4 on 2022-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('درحال برگزاری...', 'درحال برگزاری...'), ('تکمیل شده', 'تمیل شده')], default='در حال برکزاری...', max_length=100),
        ),
    ]
