# Generated by Django 4.1.4 on 2022-12-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0009_courses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('درحال برگزاری...', 'درحال برگزاری...'), ('تکمیل شده', 'تکمیل شده')], default='در حال برگزاری...', max_length=100),
        ),
    ]
