# Generated by Django 4.1.4 on 2022-12-22 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0009_courses_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AddField(
            model_name='courses',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='how_to_hold',
            field=models.CharField(choices=[('آنلاین', 'آنلاین'), ('حضوری', 'حضوری')], default='آنلاین', max_length=100),
        ),
        migrations.AddField(
            model_name='courseschild',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cover',
            field=models.FileField(upload_to='media/video_cover'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('درحال برگزاری...', 'درحال برگزاری...'), ('تکمیل شده', 'تکمیل شده'), ('به زودی', 'به زودی')], default='در حال برگزاری...', max_length=100),
        ),
    ]
