# Generated by Django 4.1.4 on 2022-12-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0010_alter_courses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
