# Generated by Django 4.1.4 on 2022-12-23 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course_app', '0011_comment_created_courseschild_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesOfCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CertificatesOfCourses', to='Course_app.courses')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CertificatesOfCourses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
