# Generated by Django 4.1.4 on 2022-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0012_certificatesofcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesofcourses',
            name='document',
            field=models.FileField(default=1, upload_to='media/course/document'),
            preserve_default=False,
        ),
    ]
