# Generated by Django 4.1.4 on 2022-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0012_alter_courses_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschild',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
