# Generated by Django 4.1.4 on 2023-01-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0013_certificatesofcourses_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
