# Generated by Django 4.1.4 on 2023-01-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0015_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.IntegerField(),
        ),
    ]
