# Generated by Django 4.1.4 on 2023-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0016_alter_checkout_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesofcourses',
            name='document_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
