# Generated by Django 4.1.4 on 2023-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0018_certificatesofcourses_image_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatesofcourses',
            name='document_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
