# Generated by Django 4.1.4 on 2023-01-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0019_alter_certificatesofcourses_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschild',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
