# Generated by Django 4.1.4 on 2023-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0020_courseschild_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
