# Generated by Django 4.1.4 on 2023-02-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0022_alter_certificatesofcourses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='end_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
