# Generated by Django 4.1.4 on 2023-02-20 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0024_alter_courses_end_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_registration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 25, 9, 21, 27, 634841, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_registration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 9, 21, 27, 619217, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
