# Generated by Django 4.1.4 on 2022-12-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.EmailField(max_length=13, unique=True, verbose_name='شماره تلفن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('student_number', models.CharField(blank=True, max_length=50, null=True)),
                ('university_name', models.CharField(choices=[('دانشگاه صنعتی سیرجان', '1'), ('دانشگاه باهنر کرمان', '2'), ('سایر دانشگاه ها', '3')], default='دانشگاه صنعتی سیرجان', max_length=100)),
                ('major', models.CharField(choices=[('مهندسی کامپیوتر', '1'), ('مهندسی برق', '2'), ('مهندسی شیمی', '3'), ('علوم کامپیوتر', '4'), ('سایر رشته ها', '5')], default='مهندسی کامپیوتر', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
