# Generated by Django 4.1.4 on 2022-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
