# Generated by Django 4.1.4 on 2022-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('مهندسی کامپیوتر', 'مهندسی کامپیوتر'), ('مهندسی برق', 'مهندسی برق'), ('مهندسی شیمی', 'مهندسی شیمی'), ('علوم کامپیوتر', 'علوم کامپیوتر'), ('سایر رشته ها', 'سایر رشته ها')], default='مهندسی کامپیوتر', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_name',
            field=models.CharField(choices=[('دانشگاه صنعتی سیرجان', 'دانشگاه صنعتی سیرجان'), ('دانشگاه باهنر کرمان', 'دانشگاه باهنر کرمان'), ('سایر دانشگاه ها', 'سایر دانشگاه ها')], default='دانشگاه صنعتی سیرجان', max_length=100),
        ),
    ]
