# Generated by Django 4.1.4 on 2022-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0005_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(default='https://www.linkedin.com/', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(default='https://www.twitter.com/', max_length=200),
        ),
    ]
