# Generated by Django 4.1.4 on 2022-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0006_user_bio_user_facebook_user_instagram_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
