# Generated by Django 4.1.4 on 2022-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0008_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
