# Generated by Django 4.1.4 on 2022-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0010_alter_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
