# Generated by Django 4.1.4 on 2022-12-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blogger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_technical_team',
            field=models.BooleanField(default=False),
        ),
    ]
