# Generated by Django 4.1.4 on 2023-01-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0019_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, choices=[('مدیر سایت و توسعه دهنده بک اند', 'مدیر سایت و توسعه دهنده بک اند'), ('توسعه دهنده فرانت اند', 'توسعه دهنده فرانت اند'), ('مدیر سئو', 'مدیر سئو'), ('مشاور و ایده پرداز', 'مشاور و ایده پرداز'), ('متخصص امنیت و شبکه', 'متخصص امنیت و شبکه'), ('برنامه نویس', 'برنامه نویس'), ('برنامه نویس ارشد', 'برنامه نویس ارشد'), ('وبلاگ نویس', 'وبلاگ نویس'), ('کارمند', 'کارمند')], default='مدرس', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('مدیر سایت و توسعه دهنده بک اند', 'مدیر سایت و توسعه دهنده بک اند'), ('توسعه دهنده فرانت اند', 'توسعه دهنده فرانت اند'), ('مدیر سئو', 'مدیر سئو'), ('مشاور و ایده پرداز', 'مشاور و ایده پرداز'), ('متخصص امنیت و شبکه', 'متخصص امنیت و شبکه'), ('برنامه نویس', 'برنامه نویس'), ('برنامه نویس ارشد', 'برنامه نویس ارشد'), ('وبلاگ نویس', 'وبلاگ نویس'), ('کارمند', 'کارمند')], default='دانشجو', max_length=150),
        ),
    ]
