# Generated by Django 4.1.4 on 2023-01-24 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0020_alter_teacher_position_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
