# Generated by Django 4.1.4 on 2022-12-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
