# Generated by Django 4.1.4 on 2022-12-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0002_blogmodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
