# Generated by Django 4.1.4 on 2022-12-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0003_alter_blogmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
