# Generated by Django 4.1.4 on 2023-01-02 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0004_blogmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
