# Generated by Django 4.1.4 on 2023-01-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0009_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-blog__id', 'parent__id')},
        ),
    ]
