# Generated by Django 4.1.4 on 2023-02-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
