# Generated by Django 4.1.4 on 2022-12-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalTeam_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicalTeamModel',
        ),
    ]
