# Generated by Django 4.1.4 on 2023-01-08 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TechnicalTeam_app', '0002_delete_technicalteammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('postion', models.CharField(choices=[('مدیر سایت و توسعه دهنده بک اند', 'مدیر سایت و توسعه دهنده بک اند'), ('توسعه دهنده فرانت اند', 'توسعه دهنده فرانت اند'), ('مدیر سئو', 'مدیر سئو'), ('مشاور و ایده پرداز', 'مشاور و ایده پرداز'), ('متخصص امنیت و شبکه', 'متخصص امنیت و شبکه'), ('برنامه نویس', 'برنامه نویس'), ('برنامه نویس ارشد', 'برنامه نویس ارشد')], default='تیم فنی', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicalteam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
