# Generated by Django 4.1.4 on 2022-12-28 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Message_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='user',
            field=models.ManyToManyField(related_name='message', to=settings.AUTH_USER_MODEL),
        ),
    ]
