# Generated by Django 4.1.4 on 2022-12-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0013_certificatesofcourses_document'),
        ('Message_App', '0002_remove_messagemodel_user_messagemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='courses',
            field=models.ManyToManyField(related_name='message', to='Course_app.courses'),
        ),
    ]
